{application,agent,
             [{description,"Distributed Erlang agent for OpenAI API"},
              {vsn,"0.1.0"},
              {registered,[agent,agent_tools,agent_registry,openai_sup,
                           openai_generator_sup,openai_clients_sup,
                           openai_generator,openai_rate_limiter,
                           openai_config]},
              {applications,[kernel,stdlib,inets,ssl,jsx]},
              {mod,{agent,[]}},
              {env,[{auto_start_groups,[chat,completions,embeddings]},
                    {output_dir,"/tmp/openai-erlang"},
                    {default_model,<<"gpt-4.1">>}]},
              {modules,[agent,agent_registry,agent_tools]}]}.
